Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.SimpleHttp
      CodeUri: /Users/aq4_admin/Documents/AWS/Code Base/serverless-app/HelloWorldFunction
      Runtime: java8.al2
      Architectures:
        - x86_64